# Generated by Django 4.1.7 on 2023-03-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=240, verbose_name="Title")),
                ("location", models.CharField(max_length=240, verbose_name="Location")),
                (
                    "level",
                    models.CharField(max_length=240, verbose_name="Experience Level"),
                ),
                ("details", models.CharField(max_length=240, verbose_name="Details")),
                (
                    "postedDate",
                    models.DateField(auto_now_add=True, verbose_name="Date Posted"),
                ),
            ],
        ),
    ]
